{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<table width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td valign="top">
            <p>
                <b>{"Customer"|i18n("design/standard/shop")}</b>
            </p>
            <p>
                {if and(is_set($order.account_information.type), $order.account_information.type|eq('persona_giuridica'))}
                    Nome: {$order.account_information.first_name|wash}<br />
                    Email: {$order.account_information.email|wash}<br />
                    Codice fiscale: {if is_set($order.account_information.vat_code)}{$order.account_information.vat_code|wash}{/if}<br />
                    Partita IVA: {if is_set($order.account_information.vat_code2)}{$order.account_information.vat_code2|wash}{/if}<br />
                    {if is_set($order.account_information.split_payment)}In regime di split payment{/if}<br />
                    {if is_set($order.account_information.fattura_elettronica_pa)}Codice IPA: {$order.account_information.codice_ipa|wash}{/if}<br />
                {else}
                    Nome: {$order.account_information.first_name|wash} {$order.account_information.last_name|wash}<br />
                    Email: {$order.account_information.email|wash}<br />
                    Codice fiscale/Partita IVA: {if is_set($order.account_information.vat_code)}{$order.account_information.vat_code|wash}{/if}<br />
                {/if}
            </p>

        </td>
        <td valign="top">

            <p>
                <b>{"Address"|i18n("design/standard/shop")}</b>
            </p>
            <p>                
                {'Street'|i18n('design/standard/shop')}: {$order.account_information.street2|wash}<br />
                {'Zip'|i18n('design/standard/shop')}: {$order.account_information.zip|wash}<br />
                {'Place'|i18n('design/standard/shop')}: {$order.account_information.place|wash} {$order.account_information.state|wash}<br />                 
                {'Country/region'|i18n('design/standard/shop')}: {$order.account_information.country|wash}<br />
            </p>
        </td>
    </tr>
</table>

{if $order.account_information.comment}
    <p>
        <b>{'Comment'|i18n( 'design/standard/shop' )}</b>
    </p>
    <p>
        {$order.account_information.comment|wash|nl2br}
    </p>
{/if}
